# Generated by Django 5.0.4 on 2024-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appxd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
