# Generated by Django 5.0.4 on 2024-05-14 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appxd', '0002_image_height_image_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='artists',
            field=models.ManyToManyField(related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
